# veredito manual (Claude) dos 500 itens: indice -> (FARMA S/N, categoria sugerida, observacao)
VO, MV = 'VITAMINA OUTRO', 'MULTIVITAMINICO'
V = {
0: ('N', 'ENERGETICO', 'bebida energetica'),
1: ('N', 'VITAMINA DE FRUTA (LANCHONETE)', 'vitamina de fruta, nao e suplemento'),
2: ('S', VO, 'Desincha capsulas'),
3: ('S', VO, 'Vivamil energetico em comprimidos (suplemento)'),
4: ('N', 'FARINHA', 'farinha de maca peruana (alimento)'),
5: ('N', 'BEBIDA FUNCIONAL', 'bebida Nutravitta lata'),
6: ('N', 'BEBIDA FUNCIONAL', 'bebida Nutravitta lata'),
7: ('N', 'LEITE DE COCO', ''),
8: ('N', 'NOZES', 'tambem tem revista no mesmo codigo'),
9: ('S', VO, 'Sundown omega 3; mesmo codigo tem gel esfoliante e Hepatilon'),
10: ('S', VO, 'Sundown selenio'),
11: ('S', VO, 'Sundown vitamina E'),
12: ('S', 'A07B ADSORBENTES INTESTINALES', 'carvao vegetal em capsulas'),
13: ('S', 'A07B ADSORBENTES INTESTINALES', 'carvao vegetal ativado capsulas'),
14: ('S', 'A07B ADSORBENTES INTESTINALES', 'carvao ativado capsulas'),
15: ('N', 'CREATINA', 'suplemento academia'),
16: ('S', VO, 'oleo de krill Essential (capsulas)'),
17: ('N', 'SUPLEMENTO PARA ACADEMIA', 'Hydrolift Essential (repositor)'),
18: ('N', 'CREATINA', ''),
19: ('N', 'CAFE CAPSULA', ''),
20: ('N', 'CAFE CAPSULA', ''),
21: ('N', 'BOLO', 'codigo com varios produtos (bolo, vasilhame, garrafa)'),
22: ('N', 'VITAMINA DE FRUTA (LANCHONETE)', ''),
23: ('S', 'M05X OUTROS PRODUTOS SISTEMA MUSCULO ESQUELETICO', 'glucosamina + condroitina'),
24: ('S', VO, 'detox supergreens capsulas'),
25: ('S', VO, 'omega 3'),
26: ('S', VO, 'multifibras Vitse'),
27: ('S', VO, 'biotina'),
28: ('S', VO, 'triptofano'),
29: ('S', VO, 'Vitse Imunese'),
30: ('S', VO, 'Vitse Concentrese'),
31: ('S', MV, 'cabelos pele e unhas capsulas'),
32: ('N', 'BEBIDA FUNCIONAL', 'After drink WOD'),
33: ('N', 'COMPLEMENTO NUTRICIONAL', 'Nutra Senior lata'),
34: ('N', 'COMPLEMENTO NUTRICIONAL', 'Nutri Dose protein po'),
35: ('S', VO, 'Teston (suplemento); mesmo codigo tem henna'),
36: ('S', VO, 'CoQ10 liquido True Source'),
37: ('N', 'BEBIDA FUNCIONAL', 'Bio Ervas liquido 300ml'),
38: ('N', 'SUPLEMENTO PARA ACADEMIA', 'energy gel'),
39: ('N', 'SUPLEMENTO PARA ACADEMIA', 'energy gel'),
40: ('N', 'COMPLEMENTO NUTRICIONAL', 'EU+ po 600g'),
41: ('N', 'HIDRATANTE INTIMO', 'gel hidratante Babasoul (cosmetico intimo)'),
42: ('S', MV, 'Forthiben cabelos e unhas'),
43: ('N', 'FERMENTO BIOLOGICO', 'levedura nutricional (alimento)'),
44: ('S', 'M03B RELAXANTES MUSCULARES ACAO CENTRAL', 'CONFLITO: ciclobenzaprina + Bye Bad + teste covid no mesmo codigo'),
45: ('N', 'BEBIDA FUNCIONAL', 'shot Kanirim'),
46: ('S', VO, 'Magnocalcio capsulas'),
47: ('S', 'FLORAL', 'floral (correlato/terapia floral)'),
48: ('S', 'FLORAL', 'floral'),
49: ('N', 'ERVA CHA', 'composto emagrecedor ervas (granel)'),
50: ('N', 'BALA PASTILHA', 'Halls'),
51: ('N', 'VESTUARIO', 'Top New (roupa)'),
52: ('S', 'A07B ADSORBENTES INTESTINALES', 'carvao ativado capsulas'),
53: ('N', 'BEBIDA FUNCIONAL', 'XY8 cha energetico sache'),
54: ('S', 'N02C9 TODAS AS OUTRAS PREPARACOES ANTI ENXAQUECA', 'CONFLITO: Neosaldina + brigadeiro/pizza no mesmo codigo'),
55: ('N', 'BOLO', 'CONFLITO: bolo + torneira'),
56: ('N', 'BATATA PALHA', 'CONFLITO: batata palha + feijao'),
57: ('N', 'VESTUARIO', 'roupa'),
58: ('N', 'FARINHA', 'casca de maracuja em po'),
59: ('N', 'COMPLEMENTO NUTRICIONAL', 'Nutren protein liquido'),
60: ('N', 'COMPLEMENTO NUTRICIONAL', 'Nutren Senior po'),
61: ('S', 'A12A CALCIO', 'Oscal Kids suspensao'),
62: ('S', 'A11C2 VITAMINA D PURA', 'Depura gotas (Sanofi)'),
63: ('S', 'A12A CALCIO', 'Oscal Cit saches'),
64: ('S', VO, 'Raia picolinato de cromo'),
65: ('S', VO, 'Raia propolvit'),
66: ('S', VO, 'Raia vitamina C + D + zinco efervescente'),
67: ('S', VO, 'Raia vitamina C + D + zinco efervescente'),
68: ('S', VO, 'Drogasil vitamina C + D + zinco efervescente'),
69: ('S', VO, 'Drogasil vitamina C + D + zinco efervescente'),
70: ('S', VO, 'Drogasil vitamina C (carga)'),
71: ('S', VO, 'Drogasil vitamina C + zinco'),
72: ('S', VO, 'Raia vitamina C + zinco'),
73: ('S', VO, 'Drogasil vitamina C + zinco'),
74: ('S', VO, 'Raia vitamina C + zinco'),
75: ('S', 'A09A DIGESTIVOS INCLUIDO ENZIMAS', 'Raia lactase'),
76: ('S', VO, 'Raia vitamina D 2000UI'),
77: ('S', VO, 'Drogasil coenzima Q10'),
78: ('S', VO, 'Drogasil coenzima Q10'),
79: ('S', VO, 'Natz cranberry + vit C e zinco'),
80: ('N', 'FIBRA ALIMENTAR', 'Natz fibras em po'),
81: ('N', 'GELEIA OUTROS', 'Natz geleia de fibras'),
82: ('N', 'ESCOVA PARA CABELO', 'Needs escova de cabelo'),
83: ('S', 'A11E1 COMPLEXO B PURO', 'complexo B gotas'),
84: ('S', VO, 'Calfon (Bayer) calcio liquido'),
85: ('N', 'FARINHA', 'maca peruana po'),
86: ('N', 'PET FARMACIA', 'Avitrin ferro para passaros'),
87: ('S', MV, 'Valda Imune Kids pastilhas (vitaminas)'),
88: ('N', 'COMPLEMENTO NUTRICIONAL', 'Pediasure'),
89: ('N', 'OLEO COCO', 'oleo de coco culinario'),
90: ('S', VO, 'oleo de linhaca capsulas'),
91: ('S', VO, 'CONFLITO: acido hialuronico capsulas + acucar de coco'),
92: ('S', 'A11G1 VITAMINA C PURA', 'Cebion gotas'),
93: ('N', 'CAFE CAPSULA', 'capsula B Blend (maquina de bebidas)'),
94: ('N', 'BEBIDA FUNCIONAL', 'shot For Me'),
95: ('N', 'BEBIDA FUNCIONAL', 'shot For Me'),
96: ('N', 'BEBIDA FUNCIONAL', 'Sleep Shot po'),
97: ('S', VO, 'seca barriga + goji capsulas'),
98: ('N', 'RODO', 'CONFLITO: rodo + furoato de mometasona creme'),
99: ('S', VO, 'vinagre de maca capsulas'),
100: ('N', 'WHEY PROTEIN', ''),
101: ('N', 'OLEO COCO', 'oleo de coco culinario'),
102: ('S', 'A12A CALCIO', 'dolomita (calcio e magnesio)'),
103: ('S', VO, 'Cobaglobal xarope (vitaminas)'),
104: ('S', 'A11G2 VITAMINA C ASSOCIADA', 'Suplevit C + zinco'),
105: ('S', MV, 'Vytinal polivitaminico'),
106: ('S', 'A11G1 VITAMINA C PURA', 'Energil C gotas'),
107: ('S', 'A11G1 VITAMINA C PURA', 'Bio C'),
108: ('N', 'CAFE CAPSULA', ''),
109: ('S', 'B03C ERITROPOIETINAS', 'Eritromax'),
110: ('S', VO, 'vitamina D3 gotas Up Vitam'),
111: ('N', 'COMPLEMENTO NUTRICIONAL', 'Novomilke po'),
112: ('S', 'D06D9 OUTROS PRODUTOS TOPICOS', 'Imunomax gel Herbarium'),
113: ('S', VO, 'Simpli D spray vitamina D'),
114: ('N', 'MEL', 'mel com propolis e guaco saches'),
115: ('N', 'ACESSORIO PARA COSMETICO', 'CONFLITO: lenco de papel + luva autobronzeador'),
116: ('S', 'MONITORAMENTO E TESTE', 'CONFLITO: teste covid + espuma de barbear'),
117: ('S', VO, 'oleo de peixe omega 3 capsulas'),
118: ('N', 'ERVA CHA', 'ginseng raiz (granel)'),
119: ('N', 'SAL', 'CONFLITO: sal marinho + levedo em po'),
120: ('S', VO, 'cha verde capsulas'),
121: ('N', 'EXTRATO DE PROPOLIS', 'extrato de propolis (MERCEARIA na arvore)'),
122: ('N', 'PRE TREINO/POS TREINO', 'C4'),
123: ('S', MV, 'Flopi mastigavel vit D e calcio'),
124: ('S', MV, 'Flopi gomas kids 12 vitaminas'),
125: ('S', MV, 'Flopi A-Z'),
126: ('S', MV, 'Flopi pirulito multivitaminico'),
127: ('S', VO, 'Flopi picolinato de cromo'),
128: ('S', VO, 'drops vitamina C'),
129: ('S', VO, 'pastilha Flopi vit C + biotina'),
130: ('S', VO, 'pastilha Flopi vitamina D'),
131: ('S', VO, 'pastilha Flopi zinco'),
132: ('S', MV, 'Life hair gomas'),
133: ('S', MV, 'Vitaley cabelo e unhas'),
134: ('N', 'COMPLEMENTO NUTRICIONAL', 'Suprasenior po'),
135: ('N', 'COMPLEMENTO NUTRICIONAL', 'Supravit diabetics po'),
136: ('N', 'PET ALIMENTO PARA AVE', 'mix para papagaio'),
137: ('S', VO, 'Raia vitamina C + D + zinco'),
138: ('N', 'FARINHA', 'maca peruana'),
139: ('N', 'FARINHA', 'maca peruana 100g'),
140: ('N', 'HIDRATANTE CORPORAL', 'leite de imersao Granado pes'),
141: ('N', 'UTILIDADE DOMESTICA', 'cesta de junco'),
142: ('S', VO, 'guarana em capsulas'),
143: ('N', 'GUARANA EM PO', ''),
144: ('N', 'COMPLEMENTO NUTRICIONAL', 'Extima lata'),
145: ('S', 'B03A2 COMBINACOES', 'Combiron gotas'),
146: ('S', VO, 'CONFLITO: Fisioton + pincel de maquiagem'),
147: ('S', 'A12A CALCIO', 'Inelatte calcio + vit D tabletes (Ache)'),
148: ('S', 'A12A CALCIO', 'Inelatte tabletes'),
149: ('S', 'A12A CALCIO', 'Inelatte tabletes'),
150: ('S', VO, 'Sitol saches (Ache)'),
151: ('S', VO, 'Sitol saches'),
152: ('S', VO, 'Propomax capsulas'),
153: ('S', 'N06E NEUROTONICOS E OUTROS', 'Forten flaconetes'),
154: ('S', MV, 'Gerivix drageas'),
155: ('S', MV, 'Neo Quimica Mulher'),
156: ('S', 'H03A PREPARADOS DE TIREOIDE', 'CONFLITO: levotiroxina + kit creme dental'),
157: ('N', 'PET FARMACIA', 'Spectramast Zoetis (veterinario)'),
158: ('S', 'A02A ANTIACIDOS ANTIFISETICOS', 'bicarbonato Farmax antiacido (na arvore: BICARBONATO, mercearia)'),
159: ('S', 'A02A ANTIACIDOS ANTIFISETICOS', 'bicarbonato Farmax'),
160: ('S', 'A02A ANTIACIDOS ANTIFISETICOS', 'bicarbonato Farmax'),
161: ('S', 'A02A ANTIACIDOS ANTIFISETICOS', 'bicarbonato medicamento'),
162: ('S', 'A11E1 COMPLEXO B PURO', 'Centromax BC liquido'),
163: ('S', MV, 'Centromax mulher'),
164: ('S', MV, 'Lavitan Energy Kids liquido'),
165: ('N', 'BALA PASTILHA', 'Valda tabletes (pastilha)'),
166: ('S', VO, 'oleo de chia capsulas'),
167: ('S', 'C05C TERAPIA VARICOSA SISTEMICA', 'castanha da india capsulas'),
168: ('N', 'BISCOITO', 'CONFLITO: Porangaba + biscoito de queijo'),
169: ('S', 'A11C2 VITAMINA D PURA', 'Cygnus D 50000UI'),
170: ('N', 'COMPLEMENTO NUTRICIONAL', 'nutricao enteral'),
171: ('N', 'COMPLEMENTO NUTRICIONAL', 'nutricao enteral'),
172: ('N', 'PAO DE QUEIJO CONGELADO', ''),
173: ('N', 'ENERGETICO', 'bebida energetica Raia'),
174: ('N', 'ENERGETICO', 'bebida energetica Raia'),
175: ('N', 'ENERGETICO', 'bebida energetica Drogasil'),
176: ('N', 'ENERGETICO', 'bebida energetica Drogasil'),
177: ('S', VO, 'berinjela capsulas'),
178: ('S', VO, 'geleia real liofilizada capsulas'),
179: ('S', 'A15A ESTIMULANTES DO APETITE', 'CONFLITO: Buclina + saco de lixo'),
180: ('N', 'PLANTA E FLOR', 'complemento com mini flor (decoracao)'),
181: ('S', VO, 'vinagre de maca capsulas'),
182: ('S', 'A06A9 OUTRAS DROGAS PARA A CONSTIPACAO', 'tintura de jalapa / aguardente alema (laxante)'),
183: ('N', 'EXTRATO DE PROPOLIS', ''),
184: ('S', 'A11E1 COMPLEXO B PURO', 'Belcomplex'),
185: ('N', 'ENERGETICO', 'energetico Relampago 10ml'),
186: ('S', MV, 'CONFLITO: Power Vita + anzol'),
187: ('S', MV, 'Mega Day A-Z'),
188: ('S', MV, 'Energin solucao oral'),
189: ('S', MV, 'kit Power Vita'),
190: ('S', MV, 'kit Lavitan Kids'),
191: ('N', 'CHINELO', 'Havaianas'),
192: ('S', VO, 'cha verde capsulas'),
193: ('N', 'SORVETE PALITO', ''),
194: ('N', 'SUBSTITUTO DE CARNE', 'proteina de soja'),
195: ('N', 'ERVA CHA', 'sene folhas'),
196: ('N', 'EXTRATO DE PROPOLIS', ''),
197: ('S', 'R05C EXPECTORANTES', 'Propaiba xarope'),
198: ('S', VO, 'CONFLITO: Ativday capsulas + tamarindo'),
199: ('N', 'ENERGETICO', 'Porreta'),
200: ('N', 'ENERGETICO', 'Porreta mix'),
201: ('N', 'SORVETE', 'Ypy Provita'),
202: ('N', 'SORVETE', 'CONFLITO: sorvete + vacina Vaxigrip'),
203: ('S', VO, 'Reformmax saches'),
204: ('S', VO, 'Reform Duo saches'),
205: ('S', VO, 'farinha de maracuja em capsulas'),
206: ('N', 'EXTRATO DE PROPOLIS', 'propolis capsulas/extrato'),
207: ('N', 'FERMENTO BIOLOGICO', 'levedo de cerveja po'),
208: ('S', 'A15A ESTIMULANTES DO APETITE', 'CONFLITO: Petivit BC + vassoura'),
209: ('N', 'ERVA CHA', 'composto emagrecedor ervas'),
210: ('S', VO, 'ferro capsulas Omix'),
211: ('S', 'DERMOCOSMETICO SOLAR', 'kit Rayito de Sol'),
212: ('N', 'SUCO PRONTO', 'Tikito'),
213: ('N', 'SUCO PRONTO', 'Tikito'),
214: ('N', 'SUCO PRONTO', 'Tikito'),
215: ('N', 'SUCO PRONTO', 'Tikito'),
216: ('N', 'SUCO PRONTO', 'Tikito'),
217: ('N', 'SUCO PRONTO', 'Tikito'),
218: ('N', 'BEBIDA FUNCIONAL', 'Forcee Sanavita po'),
219: ('N', 'BEBIDA FUNCIONAL', 'combo Sanavita'),
220: ('N', 'BEBIDA FUNCIONAL', 'Sanavita shot matinal po'),
221: ('S', VO, 'spirulina'),
222: ('S', VO, 'CONFLITO: maca peruana capsulas + garrafada'),
223: ('N', 'AMINOACIDOS', 'Movetor HMB'),
224: ('N', 'GOMA DE MASCAR', 'Trident'),
225: ('N', 'EXTRATO DE PROPOLIS', ''),
226: ('S', 'A11E1 COMPLEXO B PURO', 'CONFLITO: complexo B + manteiga de cacau'),
227: ('S', VO, 'CONFLITO: oleo de chia capsulas + cafe'),
228: ('S', VO, 'oleo de alho capsulas'),
229: ('N', 'BEBIDA FUNCIONAL', 'Bio2 po mocha'),
230: ('S', VO, 'CONFLITO: Collacel capsulas + energy po'),
231: ('S', VO, 'oleo de cartamo capsulas'),
232: ('N', 'CHA PRONTO', 'Feel Good'),
233: ('S', VO, 'oleo de abacate capsulas'),
234: ('S', VO, 'picolinato de cromo'),
235: ('S', VO, 'oleo de semente de abobora capsulas'),
236: ('S', VO, 'omega 3'),
237: ('S', VO, 'Emana gummy vinagre de maca'),
238: ('S', VO, 'cloreto de magnesio'),
239: ('N', 'ERVA CHA', 'sucupira 5g'),
240: ('N', 'ERVA CHA', 'sene 5g'),
241: ('S', VO, 'oleo de coco capsulas'),
242: ('N', 'FIBRA ALIMENTAR', 'Dauf fibras infantil liquido'),
243: ('S', 'A12A CALCIO', 'Pradocalcio'),
244: ('S', 'D11A OUTRAS PREPARACOES DERMATOLOGICAS', 'pomada de aroeira'),
245: ('N', 'LIMPADOR MULTIUSO', ''),
246: ('S', VO, 'cha verde capsulas'),
247: ('S', 'A12A CALCIO', 'CONFLITO: dolomita + farinha integral'),
248: ('S', VO, 'CONFLITO: biotina + PVPI'),
249: ('S', VO, 'Katigua 30 ervas capsulas'),
250: ('S', 'A12A CALCIO', 'dolomita'),
251: ('S', VO, 'oleo de chia com cartamo capsulas'),
252: ('N', 'ERVA CHA', 'canela de velho / extrato de amora'),
253: ('S', VO, 'Cardiosetyl liquido'),
254: ('S', VO, 'oleo de cartamo'),
255: ('S', VO, 'oleo de coco capsulas JP Pereira'),
256: ('N', 'BEBIDA FUNCIONAL', 'mistura energetica po'),
257: ('N', 'FARINHA', 'maca peruana 50g'),
258: ('N', 'BEBIDA FUNCIONAL', 'turbinado energetico po'),
259: ('N', 'OLEO ESSENCIAL', 'oleo essencial de geranio'),
260: ('S', VO, 'oleo de coco capsulas'),
261: ('S', VO, 'CONFLITO: Dprev gomas + absorvente'),
262: ('S', VO, 'melatonina gotas'),
263: ('N', 'SAL', ''),
264: ('N', 'FERMENTO BIOLOGICO', 'levedura de cerveja po'),
265: ('S', 'A07B ADSORBENTES INTESTINALES', 'carvao vegetal capsulas'),
266: ('S', MV, 'Focus Kids mastigavel'),
267: ('S', VO, 'oleo de peixe capsulas'),
268: ('S', VO, 'oleo de coco capsulas'),
269: ('N', 'ERVA CHA', 'canela de velho'),
270: ('S', VO, 'magnesio capsulas'),
271: ('S', MV, 'Cronovit Kids'),
272: ('N', 'AMINOACIDOS', 'glutamina'),
273: ('N', 'PRE TREINO/POS TREINO', ''),
274: ('S', VO, 'espirulina capsulas'),
275: ('S', MV, 'gomas cabelos e unhas'),
276: ('N', 'ERVA CHA', 'cha marcela / moringa'),
277: ('S', VO, 'canela de velho capsulas'),
278: ('N', 'HIGIENE BUCAL', 'CONFLITO: kit ortodontico + gelatina capilar'),
279: ('S', 'D08A ANTISSEPTICOS E DESINFETANTES', 'CONFLITO: PVPI + magnesio dimalato'),
280: ('S', VO, 'uxi amarelo + unha de gato capsulas'),
281: ('N', 'LINGUICA FRESCA', ''),
282: ('S', 'A05B TERAPIA HEPATICA', 'boldo flaconete'),
283: ('N', 'BEBIDA FUNCIONAL', 'One Nutrition po'),
284: ('S', VO, 'oleo de coco capsulas'),
285: ('N', 'WHEY PROTEIN', 'kit Vitamax'),
286: ('N', 'WHEY PROTEIN', 'kit Vitamax'),
287: ('N', 'WHEY PROTEIN', 'whey Vitamax'),
288: ('S', VO, 'vinagre de maca capsulas'),
289: ('N', 'HIDRATANTE CORPORAL', 'creme vitamina C Lavertuan'),
290: ('S', MV, 'kit Hair Skin Nails'),
291: ('S', MV, 'kit Hairskin Maxinutri'),
292: ('S', VO, 'omega 3'),
293: ('N', 'OLEO OUTRO', 'oleo de abacate 30ml (cosmetico/culinario)'),
294: ('S', 'A07B ADSORBENTES INTESTINALES', 'carvao vegetal capsulas'),
295: ('N', 'WHEY PROTEIN', 'proteina vegetal'),
296: ('S', 'A05B TERAPIA HEPATICA', 'Fortfig amargo'),
297: ('S', VO, 'biotina'),
298: ('S', VO, 'oleo de linhaca capsulas'),
299: ('S', MV, 'cabelos e unhas'),
300: ('S', MV, 'cabelos e unhas'),
301: ('S', VO, 'Hialure Gold acido hialuronico'),
302: ('N', 'BEBIDA FUNCIONAL', 'Rem Tea po'),
303: ('S', 'A05B TERAPIA HEPATICA', 'Confesta solucao oral boldo'),
304: ('S', VO, 'CONFLITO: curcuma/magnesio + extrato de propolis'),
305: ('N', 'FARINHA', 'ora pro nobis po'),
306: ('S', 'A07B ADSORBENTES INTESTINALES', 'carvao vegetal capsulas'),
307: ('S', VO, 'Centroflex curcuma gotas'),
308: ('S', VO, 'curcuma capsulas'),
309: ('S', MV, 'Rejucaps Hair'),
310: ('S', VO, 'omega 3 Eurofito'),
311: ('S', VO, 'Qualivita gripe forte'),
312: ('S', MV, 'multi A-Z'),
313: ('S', MV, 'Magup A-Z'),
314: ('S', MV, 'Pensevita Kids'),
315: ('N', 'PAPELARIA OUTROS', 'letra EVA'),
316: ('N', 'BEBIDA FUNCIONAL', 'acai po soluvel'),
317: ('S', 'B03A2 COMBINACOES', 'Polistar ferro + acido folico'),
318: ('N', 'WHEY PROTEIN', 'CONFLITO: whey + Vitaley cabelo e barba'),
319: ('N', 'COMPLEMENTO NUTRICIONAL', 'shake Health'),
320: ('S', 'M02A ANTIREUMATICOS TOPICOS', 'Magflan spray'),
321: ('S', VO, 'BMF Imuno capsulas'),
322: ('S', MV, 'Fabrimed Gesti (gestante)'),
323: ('N', 'BEBIDA FUNCIONAL', 'Blue Calm sache'),
324: ('N', 'ISOTONICO', 'Hydra Puravida'),
325: ('S', 'A07B ADSORBENTES INTESTINALES', 'carvao vegetal capsulas'),
326: ('S', VO, 'ioimbina capsulas'),
327: ('S', VO, 'curcuma longa capsulas'),
328: ('N', 'CARBOIDRATO', 'palatinose'),
329: ('N', 'FRUTA SECA', 'cranberry desidratado'),
330: ('S', VO, 'Desincha Neuro Boost'),
331: ('S', MV, 'Desincha Beauty'),
332: ('S', 'C04A1 VASOTERAPIA CEREBRAL E PERIFERICA', 'ginkgo + castanha da india'),
333: ('S', MV, 'Raia cabelo unhas pele'),
334: ('S', MV, 'Drogasil multivitaminico mulher'),
335: ('S', VO, 'Raia omega 3'),
336: ('N', 'SUPLEMENTO PARA ACADEMIA', 'D-ribose po'),
337: ('N', 'BEBIDA FUNCIONAL', 'Beauty In po'),
338: ('N', 'WHEY PROTEIN', 'goma proteina'),
339: ('S', VO, 'Calm Atlantica capsulas'),
340: ('N', 'PRE TREINO/POS TREINO', 'Overclock'),
341: ('S', VO, 'Sempre Fina capsulas'),
342: ('N', 'PRE TREINO/POS TREINO', 'Ectoplasma'),
343: ('S', VO, 'Ultra Magneo Force'),
344: ('S', MV, 'Femipeak cabelo pele unha'),
345: ('S', MV, 'BC Kids Ottima Vitta'),
346: ('S', VO, 'ferro Ottima Vitta'),
347: ('S', 'B03A2 COMBINACOES', 'ferro + acido folico'),
348: ('S', VO, 'Morosek softgels'),
349: ('S', VO, 'maca peruana negra capsulas'),
350: ('S', VO, 'vinagre de maca gomas'),
351: ('S', MV, 'Sthetic cabelo pele unha'),
352: ('N', 'FARINHA', 'maca peruana po'),
353: ('S', MV, 'Pharmaliv multi A-Z'),
354: ('N', 'AMINOACIDOS', 'glutamina'),
355: ('N', 'PAPEL HIGIENICO', ''),
356: ('N', 'PAPEL HIGIENICO', ''),
357: ('N', 'TOALHA DE PAPEL', ''),
358: ('N', 'TOALHA DE PAPEL', ''),
359: ('N', 'BISCOITO POLVILHO', ''),
360: ('S', VO, 'oleo de coco capsulas'),
361: ('N', 'ERVA CHA', 'cha hibisco'),
362: ('N', 'GRANOLA', ''),
363: ('S', VO, 'oleo de cartamo + coco capsulas'),
364: ('N', 'SOPA E CREME', ''),
365: ('N', 'OLEO COCO', 'culinario'),
366: ('N', 'COMPLEMENTO NUTRICIONAL', 'suplemento diet (sem detalhe)'),
367: ('N', 'TRATAMENTO CAPILAR', 'vitamina capilar Brilho da Seda'),
368: ('N', 'COMPLEMENTO NUTRICIONAL', 'Vitagit composto nutritivo'),
369: ('N', 'COMPLEMENTO NUTRICIONAL', 'Vitagit'),
370: ('N', 'BEBIDA FUNCIONAL', 'composto energetico guarana po'),
371: ('N', 'ERVA CHA', 'cascara sagrada cha'),
372: ('S', MV, 'Grow Hair'),
373: ('N', 'COMPLEMENTO NUTRICIONAL', 'Diamax'),
374: ('N', 'FERMENTO BIOLOGICO', 'levedura de cerveja'),
375: ('N', 'FARINHA', 'racao humana'),
376: ('N', 'TRATAMENTO CAPILAR', 'mascara capilar'),
377: ('S', VO, 'cha verde capsulas'),
378: ('S', 'A11C2 VITAMINA D PURA', 'Deforce K2 filmes'),
379: ('S', 'A11C2 VITAMINA D PURA', 'Deforce Flash'),
380: ('N', 'CASTANHA DE CAJU', ''),
381: ('N', 'FARINHA', 'maca peruana'),
382: ('N', 'ISOTONICO', 'bebida Athletica'),
383: ('S', VO, 'cafe verde capsulas'),
384: ('S', 'A09A DIGESTIVOS INCLUIDO ENZIMAS', 'Raia lactase'),
385: ('S', 'A09A DIGESTIVOS INCLUIDO ENZIMAS', 'Raia lactase'),
386: ('N', 'AVEIA', ''),
387: ('N', 'SAL', ''),
388: ('S', VO, 'berinjela capsulas'),
389: ('S', VO, 'oleo de coco capsulas'),
390: ('S', VO, 'oleo de cartamo capsulas'),
391: ('S', VO, 'cafeina capsulas'),
392: ('N', 'FIBRA ALIMENTAR', 'detox fibras po'),
393: ('N', 'EXTRATO DE PROPOLIS', ''),
394: ('N', 'PET FARMACIA', 'Vitacanis (caes)'),
395: ('N', 'LEITE DE COCO', ''),
396: ('S', VO, 'maca peruana capsulas'),
397: ('S', VO, 'ZMA + maca capsulas'),
398: ('N', 'CREME DE AMENDOIM', ''),
399: ('S', 'M05X OUTROS PRODUTOS SISTEMA MUSCULO ESQUELETICO', 'Artrotabs'),
400: ('N', 'FARINHA', 'maca peruana'),
401: ('N', 'COMPLEMENTO NUTRICIONAL', 'Sustevit'),
402: ('N', 'OLEO ESSENCIAL', 'oleo de hortela'),
403: ('S', MV, 'B-Well Beauty'),
404: ('S', MV, 'B-Well Maternity'),
405: ('S', VO, 'B-Well luteina'),
406: ('S', VO, 'oleo de primula'),
407: ('S', VO, 'Drogasil cafeina'),
408: ('S', 'A12A CALCIO', 'Drogasil calcio + D'),
409: ('S', VO, 'Raia omega 3'),
410: ('S', VO, 'Raia cafeina'),
411: ('S', VO, 'Raia linhaca'),
412: ('S', VO, 'Raia primula'),
413: ('S', VO, 'Raia vitamina D 1000UI'),
414: ('S', VO, 'CoQ10'),
415: ('N', 'PET ALIMENTO PARA CACHORRO', 'racao'),
416: ('S', MV, 'Ogestan Gold'),
417: ('S', VO, 'berinjela capsulas'),
418: ('N', 'FERMENTO BIOLOGICO', 'levedo de cerveja'),
419: ('S', VO, 'Lipix Plus'),
420: ('N', 'BEBIDA FUNCIONAL', 'Energy Up'),
421: ('N', 'ERVA CHA', 'cha seca barriga'),
422: ('N', 'CASTANHA DE CAJU', ''),
423: ('N', 'OVO VERMELHO', ''),
424: ('N', 'BEBIDA FUNCIONAL', 'New Skin colageno po'),
425: ('S', VO, 'oleo de alho capsulas'),
426: ('S', VO, 'oleo de alho capsulas'),
427: ('N', 'FARINHA', 'maca peruana po'),
428: ('N', 'ERVA CHA', 'green tea'),
429: ('S', VO, 'spirulina capsulas'),
430: ('N', 'CAFE CAPSULA', 'capsula B Blend'),
431: ('S', VO, 'omega 3'),
432: ('S', VO, 'omega 3'),
433: ('N', 'WHEY PROTEIN', 'proteina vegetal'),
434: ('N', 'EXTRATO DE PROPOLIS', ''),
435: ('S', 'A06A3 INCREMENTADORES DO BOLO INTESTINAL', 'psyllium'),
436: ('S', MV, 'Happy imunidade (gomas)'),
437: ('N', 'BOLO TRADICIONAL', ''),
438: ('N', 'ENERGETICO', ''),
439: ('S', VO, 'oleo de cartamo'),
440: ('N', 'SUCO PRONTO', ''),
441: ('S', VO, 'geleia real capsulas'),
442: ('N', 'PET ALIMENTO BOVINO', 'Minercorte (gado)'),
443: ('N', 'SUCO PRONTO', ''),
444: ('S', VO, 'oleo de coco capsulas'),
445: ('S', VO, 'Cafex cafeina'),
446: ('N', 'TRATAMENTO CAPILAR', 'complexo vitaminico capilar'),
447: ('S', VO, 'oleo de coco capsulas'),
448: ('S', VO, 'maca peruana capsulas'),
449: ('N', 'PET ALIMENTO BOVINO', 'mineral para gado'),
450: ('S', VO, 'oleo de alho capsulas'),
451: ('S', 'A11C2 VITAMINA D PURA', 'Supramax D'),
452: ('N', 'EXTRATO DE PROPOLIS', 'propolis capsulas'),
453: ('N', 'COCO RALADO', ''),
454: ('S', VO, 'Regulare saches (fibras)'),
455: ('S', 'FRALDA GERIATRICA', 'fralda geriatrica (correlato)'),
456: ('S', VO, 'triptofano'),
457: ('N', 'FARINHA', 'maca peruana'),
458: ('S', 'C05C TERAPIA VARICOSA SISTEMICA', 'castanha da india'),
459: ('S', VO, 'oleo 5 em 1 capsulas'),
460: ('S', VO, 'CONFLITO: oleo de coco capsulas + oleo de menta'),
461: ('N', 'TRATAMENTO CAPILAR', 'Caps Liso Revival'),
462: ('N', 'SUPLEMENTO PARA ACADEMIA', 'Tasty Iso'),
463: ('N', 'FERMENTO BIOLOGICO', 'CONFLITO: nutritional yeast + quitosana'),
464: ('N', 'FERMENTO BIOLOGICO', 'nutritional yeast'),
465: ('S', VO, 'oleo de semente de abobora gotas'),
466: ('N', 'CREATINA', ''),
467: ('S', 'A07B ADSORBENTES INTESTINALES', 'carvao vegetal'),
468: ('S', 'A06A9 OUTRAS DROGAS PARA A CONSTIPACAO', 'cascara sagrada capsulas'),
469: ('N', 'AMINOACIDOS', 'glutamina'),
470: ('S', 'A05B TERAPIA HEPATICA', 'Epadose'),
471: ('S', 'DERMOCOSMETICO CAPILAR', 'tonico antiqueda Cronoliv'),
472: ('N', 'AMINOACIDOS', 'glutamina'),
473: ('S', 'A05B TERAPIA HEPATICA', 'Megabil flaconete'),
474: ('S', 'MONITORAMENTO E TESTE', 'termometro'),
475: ('S', VO, 'vitamina C Dr Good'),
476: ('S', VO, 'picolinato de cromo'),
477: ('N', 'MAQUIAGEM OLHOS', 'mascara de cilios'),
478: ('S', MV, 'Hair Up gomas'),
479: ('S', MV, 'Control Plus A-Z'),
480: ('N', 'BEBIDA FUNCIONAL', 'ora pro nobis po'),
481: ('N', 'BEBIDA FUNCIONAL', 'ora pro nobis po'),
482: ('S', VO, 'Cimevitan Testo'),
483: ('N', 'EXTRATO DE PROPOLIS', 'propolis + vit D'),
484: ('S', VO, 'Vitaley Lino Plus'),
485: ('S', MV, 'Biocentro cabelo e barba'),
486: ('S', 'B03A2 COMBINACOES', 'ferro + B12'),
487: ('N', 'SUPLEMENTO PARA ACADEMIA', 'Hydrolift'),
488: ('N', 'SUPLEMENTO PARA ACADEMIA', 'Hydrolift'),
489: ('N', 'SUPLEMENTO PARA ACADEMIA', 'Hydrolift'),
490: ('S', VO, 'NAC Plus'),
491: ('S', MV, 'Belissima Haski'),
492: ('N', 'BEBIDA FUNCIONAL', 'ora pro nobis po'),
493: ('S', VO, 'vinagre de maca gomas'),
494: ('S', MV, 'A-Z Centrum'),
495: ('S', MV, 'Vit Glaft'),
496: ('N', 'BISCOITO', 'CONFLITO: sequilho + Trifor saches'),
497: ('N', 'CHOCOLATE BOMBOM', 'CONFLITO: bombom + Betricort pomada'),
498: ('S', 'A07B ADSORBENTES INTESTINALES', 'carvao vegetal'),
499: ('S', MV, 'CONFLITO: Lavitan Memoria + servico de entrega'),
}

# nomes que não existem na árvore -> nome real
MAPA = {'A07B ADSORBENTES INTESTINALES': 'A07B ADSORBENTES INTESTINALES ANTIDIARREICOS', 'A05B TERAPIA HEPATICA': 'A05B PRODUTOS PARA DOENCAS DO FIGADO HEPATOPROTETORES',
  'A02A ANTIACIDOS ANTIFISETICOS': 'A02A1 ANTIACIDOS PUROS', 'BEBIDA FUNCIONAL': 'COMPLEMENTO NUTRICIONAL', 'FARINHA': 'FARINHA OUTROS', 'FIBRA ALIMENTAR': 'COMPLEMENTO NUTRICIONAL',
  'TRATAMENTO CAPILAR': 'MASCARA E CREME DE HID. CAPILAR', 'SAL': 'SAL SAUDAVEL', 'VITAMINA DE FRUTA (LANCHONETE)': 'SUCO PRONTO', 'BOLO': 'BOLO TRADICIONAL',
  'FLORAL': 'CORRELATO OUTROS', 'VESTUARIO': 'VESTUARIO OUTROS', 'HIDRATANTE CORPORAL': 'HIDRATANTE CORPORAL OUTROS', 'BISCOITO': 'BISCOITO SALGADO OUTROS',
  'SORVETE': 'SORVETE PALITO', 'OLEO ESSENCIAL': 'AROMA E ESSENCIA', 'TOALHA DE PAPEL': 'TOALHA DE PAPEL ROLO', 'PET ALIMENTO BOVINO': 'PET ALIMENTO BOVINO E EQUINO',
  'MEL': 'COMPOSTO DE MEL', 'HIGIENE BUCAL': 'ACESSORIO HIGIENE DENTAL', 'MAQUIAGEM OLHOS': 'MASCARA DE CILIOS', 'CHA PRONTO': 'CHA PRONTO COMUM',
  'ACESSORIO PARA COSMETICO': 'ACESSORIO PARA COSMETICA', 'UTILIDADE DOMESTICA': 'UTILIDADE OUTROS', 'GOMA DE MASCAR': 'GOMA DE MASCAR', 'OVO VERMELHO': 'OVO CAIPIRA',
  'PET FARMACIA': 'MEDICAMENTO CAES E GATOS OUTROS', 'HIDRATANTE INTIMO': 'LUBRIFICANTE INTIMO GEL', 'SUPLEMENTO PARA ACADEMIA': 'CARBOIDRATO',
  'PET ALIMENTO PARA CACHORRO': 'PET ALIMENTO OUTROS', 'LIMPADOR MULTIUSO': 'LIMPADOR MULTIUSO', 'D11A OUTRAS PREPARACOES DERMATOLOGICAS': 'D11A OUTRAS PREPARACOES DERMATOLOGICAS INCL XAMPUS MED',
  'D06D9 OUTROS PRODUTOS TOPICOS': 'D06D9 OUTROS PRODUTOS TOPICOS PARA INFECOES VIRAIS'}
V[41] = ('S', 'HIDRATANTE INTIMO', 'gel intimo Babasoul (lubrificante/hidratante intimo e cesta Farmacia na arvore)')
for k in (17, 487, 488, 489, 462): V[k] = ('N', 'ISOTONICO', V[k][2])
V[8] = ('N', 'NOZES', V[8][2]); V[201] = ('N', 'SORVETE', V[201][2]); V[202] = ('N', 'SORVETE', V[202][2])
V[1] = ('N', 'SUCO PRONTO', 'vitamina de fruta (lanchonete), nao e suplemento'); V[22] = ('N', 'SUCO PRONTO', 'vitamina de fruta (lanchonete)')
for i, (f, cat, obs) in list(V.items()): V[i] = (f, MAPA.get(cat, cat), obs)
MAPA2 = {'D08A ANTISSEPTICOS E DESINFETANTES': 'D08A ANTISSEPTICOS E DESINFETANTES EXCL CURATIVOS MEDIC', 'M02A ANTIREUMATICOS TOPICOS': 'M02A ANTIREUMATICOS TOPICOS COM ANALGESICOS',
  'C04A1 VASOTERAPIA CEREBRAL E PERIFERICA': 'C04A1 VASOTERAPIA CEREBRAL E PERIF EXCLUINDO ANTAG CALC'}
for i, (f, cat, obs) in list(V.items()): V[i] = (f, MAPA2.get(cat, cat), obs)
